server:
  port: 8081
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#  mvc:
#    async:
#      request-timeout: 100000
#knife4j:
#  enable: true

# Win端
spadas:
  file:
    # 硬盘存储路径,起始路径为项目根路径
    #    baseUri: ./dataset/argoverse
    baseUri: ./dataset-mini/
    # 网页请求路径
    staticUri: /dataset-mini/
